### ISSUE TITLE
Create a Service-Locator for SFX.

### ISSUE THREAD

**Issue by tyskwo** [tyskwo/OfficeMayhem#15]
## Description

Sound code is sprinkled throughout the entire codebase; it needs to be decoupled. A [service locator](http://gameprogrammingpatterns.com/service-locator.html) would decouple this while staying a clean solution.

## Plan of Action

Implement similarly to [this](http://gameprogrammingpatterns.com/service-locator.html), see pros and cons and *Design Decisions*.

## Open Problems

It would affect the entire codebase, this is an issue that should be dealt in solidarity.

## Affected Classes

Most of them.

**Comment by Scum42** [comment]
Forgot to do this in the commit. Refactoring is done, which officially closes this task.
